import Image1 from "./assets/image1.png";
import Image2 from "./assets/image2.png";
import userImage from "./assets/user.png";
import userImage2 from "./assets/user2.png";

const data = [
  {
    id: 1,
    image: Image1,
    title: "New Apartment Nice View",
    address: "Quincy St, Brooklyn, NY, USA",
    specs: {
      user: userImage,
      bed: "8",
      bath: "5",
      garage: "1",
      area: "1200 Sq Ft",
    },
    price: "7,500",
  },
  {
    id: 2,
    image: Image2,
    title: "Old Apartment Nice View",
    address: "Quincy St, Brooklyn, NY, USA",
    specs: {
      user: userImage2,
      bed: "10",
      bath: "5",
      garage: "1",
      area: "1200 Sq Ft",
    },
    price: "7,500",
  },
  {
    id: 3,
    image: Image1,
    title: "Beatiful Apartment Nice View",
    address: "Quincy St, Brooklyn, NY, USA",
    specs: {
      user: userImage,
      bed: "5",
      bath: "5",
      garage: "1",
      area: "1200 Sq Ft",
    },
    price: "7,500",
  },
  {
    id: 4,
    image: Image2,
    title: "Cozy Apartment Nice View",
    address: "Quincy St, Brooklyn, NY, USA",
    specs: {
      user: userImage2,
      bed: "4",
      bath: "5",
      garage: "1",
      area: "1200 Sq Ft",
    },
    price: "7,500",
  },
  {
    id: 5,
    image: Image1,
    title: "Futuristic Nice View House",
    address: "Quincy St, Brooklyn, NY, USA",
    specs: {
      user: userImage,
      bed: "5",
      bath: "5",
      garage: "1",
      area: "1200 Sq Ft",
    },
    price: "7,500",
  },
  {
    id: 6,
    image: Image1,
    title: "Exotic Apartment Nice View",
    address: "Quincy St, Brooklyn, NY, USA",
    specs: {
      user: userImage2,
      bed: "5",
      bath: "4",
      garage: "1",
      area: "1200 Sq Ft",
    },
    price: "7,500",
  },
  {
    id: 7,
    image: Image2,
    title: "Futuristic Nice View House",
    address: "Brooklyn Quincy St, NY, USA",
    specs: {
      user: userImage,
      bed: "5",
      bath: "5",
      garage: "1",
      area: "1200 Sq Ft",
    },
    price: "7,500",
  },
  {
    id: 8,
    image: Image1,
    title: "Classy Style House",
    address: "Quincy St, Brooklyn, NY, USA",
    specs: {
      user: userImage2,
      bed: "5",
      bath: "5",
      garage: "1",
      area: "1200 Sq Ft",
    },
    price: "7,500",
  },
  {
    id: 9,
    image: Image2,
    title: "New Apartment Nice View",
    address: "George St, Brooklyn, NY, USA",
    specs: {
      user: userImage,
      bed: "5",
      bath: "5",
      garage: "1",
      area: "1200 Sq Ft",
    },
    price: "7,500",
  },
  {
    id: 10,
    image: Image1,
    title: "Classy Style House",
    address: "Quincy St, Brooklyn, NY, USA",
    specs: {
      user: userImage2,
      bed: "5",
      bath: "5",
      garage: "1",
      area: "1200 Sq Ft",
    },
    price: "7,500",
  },
  {
    id: 11,
    image: Image1,
    title: "New Apartment Nice View",
    address: "Washington St, Brooklyn, NY, USA",
    specs: {
      user: userImage,
      bed: "5",
      bath: "5",
      garage: "1",
      area: "1200 Sq Ft",
    },
    price: "7,500",
  },
  {
    id: 12,
    image: Image2,
    title: "New Apartment Nice View",
    address: "Maryland St, Brooklyn, NY, USA",
    specs: {
      user: userImage2,
      bed: "5",
      bath: "5",
      garage: "1",
      area: "1200 Sq Ft",
    },
    price: "7,500",
  },
];

export default data;
